theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
title: Agile Leadership Remote by Milena
description: I am Milena, a software developer, agile practicioner, coach and leader and a remote work enthusiast. 
author: Milena-Mercedes May
